Real-Dev-Squad/website-members

.eslintignore
.eslintrc.js
.prettierignore
.prettierrc
.stylelintrc.json
components/pages/index/index.js
components/preview-member/index.js
next.config.js
package.json
pages/index.js
pages/members/[id]/index.js
styles/global-styles.scss

To maintain code quality and formatting this PR integrates ESLint, Prettier, pre-commit hooks using husky. 
Note: ESLint and Prettier configs are very standard, we can add more plugins or configs in the future.

Adding ESLint, Prettier and pre-commit hooks. 

---

components/member-list-item/member-list-item.module.scss

member list hover minor css update for members

---

components/footer/footer.module.scss
components/footer/index.js
pages/_app.js

Footer Data Formatting

---

components/member-list-item/member-list-item.module.scss

As discussed in the call, have made image hover changes, icon scale on hover changes and box shadow

addition of icon change border update imagechange

---

components/footer/footer.module.scss
components/footer/index.js
pages/_app.js
styles/global-styles.scss
styles/layout-style.module.scss

This PR solves issue #30 , and issue #29 creating base layout is already there in _app.js I added styling to that so, that main component should have some padding and footer should always remain at bottom. I used css modules, so any previous styling would not break.

footer always on bottom solved and base layout component added with proper styling

---

components/footer/footer.module.scss
components/member-profile/index.js
components/member-profile/member-profile.module.scss
pages/members/[id]/index.js

https://github.com/Real-Dev-Squad/website-members/issues/31

Added fetaure that displays image and name in profile edit

---

components/member-list-item/member-list-item.module.scss

css changes for name padding and icon

Css restoration

---

components/member-list-item/member-list-item.module.scss

There is major development going here 😂

Final CSS changes

---

README.md

I have linked the member's page in README.md file.
Fixes #45

Linked Member's Page

---

git-hooks/pre-commit.js
git-hooks/pre-push.js
package-lock.json
package.json
util/generic-functions.util.js

Solves #57 
Added
- Pre Commit hook to check for
- linting
- branch name
- Pre Push hook to pull from upstream/origin before push
Code is commented because I am not sure what should be the name of remote (it will depend on the developer)

Introduce git-hooks

---

components/member-list-item/index.js
components/members-list/index.js
components/pages/index.js
components/social-media-icon/social-media.constant.js
pages/index.js

This is in reference to issue #53 
(WIP PR)

Added the logic to fetch member details Also in SSR

---

components/member-profile/index.js
helper-functions/fetch.js
helper-functions/getPRs.js
package-lock.json
package.json

Fixes #77 
~~To do:~~
~~- [ ]  Limit the PRs: maybe 3 or 5 or whatever we decide~~
~~- [ ]  Handle the state (not react state) of readyForReview better when the PR is closed. Currently I'm sending empty string which shows a dot if the PR is closed. (refer screenshots)~~
Please review and let me know if any changes are required.
Thank you! 😄

Fetching and displaying PRs on individual member page

---

package-lock.json
package.json

Upgraded packages

---

components/member-list-item/index.js
package-lock.json
pages/[id]/index.js

Changed the route of individual member for '/memers/user' to '/user'.
closes #82

changed route of individual member page from /members/user to /user

---

components/member-list-item/index.js
components/member-profile/index.js
package-lock.json
package.json
pages/_app.js

When user clicks on any of the profile card, then image from that profile card animate and travels to next page's position of member image and cling to that.
https://user-images.githubusercontent.com/26649558/104850760-fd5fd200-5916-11eb-819c-c384fad81efe.mp4

Adds user profile animation

---

components/member-profile/contribution/contribution.module.scss
components/member-profile/contribution/index.js
components/member-profile/contribution/pr-link/index.js
components/member-profile/contribution/pr-link/pr-link.module.scss
components/member-profile/index.js
components/member-profile/member-profile.module.scss
helper-functions/time-was.js
helper-functions/urls.js
pages/[id]/index.js

Ref to issue #90 
This is how it looks

Show contribution details on member profile page

---

package.json

Fixes linting scripts

---

.github/workflows/continuous-integration.yml

Adds CI using Github Actions
Fixes #112

Adds CI using Github Actions

---

components/UI/side-drawer/index.js

The issue for ESlint error in side-drawer component is fixed.

Eslint side-drawer error fixed

---

components/member-list-item/index.js

Profile page opens on clicking anywhere on the member card

Click event added to member card

---

CONTRIBUTING.md

Updating CONTRIBUTING.md to adapt to git flow

---

components/member-list-item/index.js
components/member-profile/index.js
helper-functions/urls.js
jsconfig.json
package-lock.json
pages/[id]/index.js
pages/index.js

changed the base baseURL. imageURL is still same

changes done in the baseURL.

---

components/member-profile/member-profile.module.scss

Changed width to 100% in mobile

---

components/member-profile/contribution-type/contributions-type.module.scss
components/member-profile/member-profile.module.scss
styles/global-styles.scss

Contributions container design fix

---

components/member-profile/contribution-type/index.js
components/member-profile/contribution/contribution.module.scss
components/member-profile/contribution/index.js
components/member-profile/contribution/pr-link/index.js
components/member-profile/contribution/pr-link/pr-link.module.scss

@sumitd94 I have made changes according to the new Figma Design. Please review the PR.
Desktop mode
Mobile Devices

contribution UI as per figma design

---

components/member-profile/contribution-type/index.js
components/member-profile/contribution/index.js
components/member-profile/index.js
package-lock.json
pages/[id]/index.js

Changes related to issue 168.
closes 168

Removed badges and tech stack if the user is not dev

---

components/member-card/card.module.scss
components/member-card/index.js
components/new-member-list-item/index.js
components/new-member-list/index.js
components/pages/index.js

made necessary changes

---

components/member-card/card.module.scss
components/member-card/index.js
components/members-list/member-list.module.scss
components/new-member-list/new-member-list.module.scss
pages/index.js

change in design for new member section

---

components/member-card/card.module.scss

Made some changes on new member section

some enhancements for new member section

---

pages/_document.js

i have added the necessary lang attribute to the html tag.

added lang attribute to html element

---

.babelrc
.eslintrc.js
jest.config.js
jest.setup.js
package-lock.json
package.json
test/unit/components/member-card/index.test.js

This PR Includes the Jest setup for `website-members`
- Wrote a simple test to make sure it's working.

Jest setup

---

components/UI/backdrop/index.js
components/UI/navbar/index.js
components/UI/side-drawer/index.js
components/UI/spinner/index.js
components/footer/index.js
components/member-card/index.js
components/member-list-item/index.js
components/member-profile/active-task/index.js
components/member-profile/contribution-type/index.js
components/member-profile/contribution/index.js
components/member-profile/contribution/pr-link/index.js
components/member-profile/index.js
components/members-list/index.js
components/modal/Header/index.js
components/modal/Register/index.js
components/modal/index.js
components/new-member-list-item/index.js
components/new-member-list/index.js
components/not-found-page/index.js
components/pages/index.js
components/social-media-icon/index.js
pages/[id]/index.js
pages/_app.js
pages/index.js

updated imports to absolute imports based on jsconfig `baseUrl`.

made imports absolute

---

components/member-profile/contribution/index.js
package-lock.json

Redirect the Checkout this feature in Action link in Members profile to Feature Url

Redirected to the featureUrl

---

components/member-profile/member-profile.module.scss

Remove the hover effect from contribution container

---

components/member-profile/active-task/active-task.module.scss
components/member-profile/active-task/index.js
helper-functions/estimated-days.js
helper-functions/progressIndicator.js
helper-functions/showProgressIndicator.js
helper-functions/taskProgress.js

Progress Indicator for Active tasks

---

components/member-card/card.module.scss

Please refer to the screenshots for better understanding.

removed border for new members and spacing for members

---

components/member-profile/member-profile.module.scss

Profile overview section to the top

---

src/components/member-profile/contribution/contribution.module.scss

reference https://github.com/Real-Dev-Squad/website-members/pull/242

removed hover effect

---

src/pages/[id]/index.js

disable cache for active tasks

---

src/components/member-card/card.module.scss

Fix: Transition on members card

---

package-lock.json
package.json
src/components/member-profile/contribution-type/index.js
src/components/member-profile/index.js
src/pages/[id]/index.js

Fixed the fetching and displaying of active tasks

---

jest.config.js
package.json
src/components/member-profile/active-task/index.js
src/test/unit/components/active-task/index.test.js

added test for active-task progress

---

src/components/member-card/index.js
src/constants/AppConstants.js

Linked Issues :
Closes #287 
Closes #288 
- Reduced Long hover time from 3 sec to 1 sec
- Removed a check which restricts super-user to not have settings on members card
Enhancement
Before:
After:

Reduced long hover time and removed a check

---

src/pages/index.js

this temporarily resolves #300

hotfix: Image issue

---

src/components/member-profile/contribution/index.js

Closes #306 
Added a optional chaining check for URL.
Yes

Fix contribution component

---

src/components/member-card/index.js

Change to avoid fetching image from static site for new members
https://github.com/Real-Dev-Squad/website-members/issues/311#event-5899126198

use placedholder image for new members

---

.eslintrc.js
.prettierrc
src/components/member-profile/index.js
src/components/member-profile/mock/get-badges.js
src/custom-hooks/useFetch.js
src/helper-functions/fetch.js
src/pages/[id]/index.js
src/pages/index.js

**This PR fixes the issue as mentioned in the issue https://github.com/Real-Dev-Squad/website-members/issues/294**
- Disabled **no-alert** rule.
- Renamed/Replaced unnamed functions with named functions or es6 arrow functions
- Updated the dependencies of UseEffect dependency array as per eslint warning

Fix eslint warnings

---

src/components/UI/navbar/navbar.module.scss
src/components/UI/search-box/index.js
src/components/UI/search-box/search-box.module.scss
src/components/home/index.js
src/components/members/index.js
src/components/new-members/index.js
src/constants/AppConstants.js
src/helper-functions/search-members.js
src/pages/_app.js
src/store/search-members/searchMembers-context.js

Closes #164
Now we have a search box on the website. If you want to search for a member, you can type the member's name inside the search box and you will get a particular member's card.
- No. It is a feature.
https://user-images.githubusercontent.com/70262783/152112092-431637dd-46f4-4c9b-ac11-7c48267b6022.mp4

added search members feature

---

src/pages/index.js

Removing the dev flag condition for cloudinary images
- Expected
- Actual

turn on cloudinary images live

---

src/components/UI/navbar/navbar.module.scss
src/components/home/index.js
src/components/member-profile/member-profile.module.scss
src/components/member-role-update/index.js
src/pages/index.js

sync develop with main

---

src/components/member-role-update/index.js
src/pages/[id]/index.js

Removal of dev feature flag for profile picture on members page.
Closes issue https://github.com/Real-Dev-Squad/website-members/issues/369
No 
Before - 
After -

fix: remove dev flag for cloudinary

---

src/components/member-role-update/index.js
src/helper-functions/urls.js
src/pages/[id]/index.js

Sync main to dev

---

src/components/member-role-update/index.js
src/constants/AppConstants.js

Changed Text from "New Members" to "New Users"
Visuals:
Before Changes:
After Changes:

fix-textChange

---

package.json

dev script updated in package.json to run multiple npm scripts in parallel.
closes #411

dev script updated in package.json

---

src/api/UserDataApi.js
src/api/UserTasksApi.js
src/components/user-profile/index.js
src/constants/error-messages.js
src/pages/[id]/index.js
src/store/user/user-context.js

Issue: https://github.com/Real-Dev-Squad/website-members/issues/367
- Only Super Users should be able to view the Non-Members Profile page.
Yes
- Expected
- Actual

Profile page of nonMembers only to be visible to SuperUsers.

---

src/components/user-profile/index.js
src/store/user/user-context.js

Yes
https://github.com/Real-Dev-Squad/website-members/issues/430
- Expected
- Actual

[#430] wrapped useCallBack hook in setUserPrevilages and refactored the code

---

src/constants/AppConstants.js
src/pages/_app.js
src/store/keyboard/context.js

closes #420 . Added a listener on the root div which listens for alt key presses and sets isOptionKey to true.
no

added global alt key listener

---

src/components/UI/backdrop/backdrop.module.scss

Background Blur added to modal.

background blur feature added to modal

---

src/components/member-role-update/index.js
src/components/member-tag-assign/index.js
src/helper-functions/action-handlers.js
src/helper-functions/urls.js
src/test/unit/components/member-tag-assign/index.test.js

Created a component that provides an options to add tags to the user.
closes #502 
No

Create component to assign users tags

---

src/components/keyboard-handler/index.js
src/components/util/KeyboardHandler.js
src/pages/_app.js
src/store/keyboard/context.js

Add event listeners for option key on document

Fix superUser option key hold to show settings icon

---

src/components/keyboard-handler/index.js
src/components/new-members/index.js
src/pages/_app.js
src/store/keyboard/context.js

Sync dev to main ( Prod release: Super user option key issue, alt key press to open user page )

---

src/components/keyboard-handler/index.js
src/components/member-card/super-user-options/index.js
src/components/new-members/index.js
src/pages/_app.js
src/store/keyboard/context.js

sync dev to main

---

.env.staging
package.json
src/components/member-profile/index.js
src/helper-functions/urls.js

add staging config and maintain consistency in api urls

---

.env.development
src/helper-functions/search-members.js

The staging set up failed as we noticed a few users did not have their names entered, i.e. they had incomplete user details
- used Optional chaining to resolve it.
Yes
- Expected
- should show up names of all users on the website
- Bug
- fails to show as some users have not filled in their details

Fix nextjs errors for users with incomplete user details

---

src/components/keyboard-handler/index.js
src/helper-functions/search-members.js

sync dev to main [ release alt key issue ]

---

src/components/keyboard-handler/index.js
src/pages/index.js

Date: 02/08/2023
Developer Name: @manish591 
PR Number(s):- 
1. https://github.com/Real-Dev-Squad/website-members/pull/543
Issue Ticket Number:-
1. https://github.com/Real-Dev-Squad/website-members/issues/541
Backend changes
Frontend Changes
Database changes
Breaking changes (If your feature is breaking/missing something please mention pending tickets)
Deployment notes
Any special instructions for the deployment
Tested in staging
Also, attach their screenshots.
Tested with realdevsqaud API
Staging proof:

Dev to Main Sync

---

src/components/keyboard-handler/index.js
src/components/member-profile/index.js
src/components/member-profile/member-profile.module.scss
src/components/member-role-update/index.js
src/helper-functions/action-handlers.js
src/helper-functions/urls.js

Date: 08/06/2023
Developer Name: @Pratiyushkumar 
PR Number(s):- #536 
Issue Ticket Number:- #533  #539 
Backend changes
No
Frontend Changes
Yes
Database changes
No
Breaking changes (If your feature is breaking/missing something please mention pending tickets)
No
Deployment notes
NA
Tested in staging
Yes
Also, attach their screenshots.
https://github.com/Real-Dev-Squad/website-api-contracts/tree/main/users#patch-usersidtemporarydata 
**Follow-Up issue**
so testing was failing so this issue is created to tackle the testing issue
https://github.com/Real-Dev-Squad/website-members/issues/548

Provide super user option on member detail page (#536)

---

src/constants/AppConstants.js

Hiding the "Crypto" section from the "website-member" navbar.
Fixes #551. 
- Expected
- Actual

Comment out crypto section from navbar

---

jest.config.js
src/constants/AppConstants.js
src/store/keyboard/context.js
src/test/unit/components/member-profile/index.test.js

* Comment out crypto section from navbar
* remove commented code
- Expected
- Actual

Dev to main Sync 

---

.env.development
src/components/member-profile/index.js
src/components/member-role-update/index.js
src/components/member-role-update/member-role-update.module.scss
src/helper-functions/action-handlers.js
src/styles/constants/_colors.scss
src/test/unit/components/member-profile/index.test.js

**Issue - #550**
Added Reason text box in the archiving process
- Expected
- Actualo
https://github.com/Real-Dev-Squad/website-members/assets/75125943/5b90d0b9-ff5a-4d58-a40b-92f1c9455da9

added reason text box in archiving process

---

src/components/member-profile/contribution-type/contributions-type.module.scss
src/components/member-profile/contribution-type/index.js
src/constants/error-messages.js
src/helper-functions/urls.js
src/test/unit/components/member-profile/index.test.js

Fixes: https://github.com/Real-Dev-Squad/website-members/issues/540
Design Doc: https://docs.google.com/document/d/1JQ4wgYqY9cN3MLiPLpgdR_ivudZRiPPZTATb1cZGJlI/edit?usp=sharing 
1.  Task status filter API parameter updated.
2. Empty error msgs rendered if no data from api.
Yes
1. Go to members site and open any member 
https://members.realdevsquad.com/ankush 
2. Open N/W tab, you will see task status api failing.
3. On UI if end user click on accordian button then it was not expanding due to no data inside.
- Expected
API should return 200 and accordian should show error msg inside if no data returns from api.
- Actual
API gives 404.
Before:
After changes:
Desktop View:
Mobile View:
API/N/w Tab:
Test Coverage:

updated activetask api parameter and accordion section

---

src/components/member-profile/active-task/index.js
src/components/member-profile/contribution-type/index.js
src/components/member-profile/contribution/index.js
src/helper-functions/taskProgress.js
src/helper-functions/time-was.js
src/test/unit/components/member-profile/index.test.js

Fixes https://github.com/Real-Dev-Squad/website-members/issues/569
Removal of feature flag from 2 bug fixes related to below merged MR.
https://github.com/Real-Dev-Squad/website-members/pull/561
https://github.com/Real-Dev-Squad/website-members/pull/565
No
NA
- Before
It needed a feature flag for below scenario
- After - without need of feature flag.
Scenario 1: Invalid Date
Scenario 2: Expanding accordian section with no data)
Test results:

removed feature flag from accordian and invalid date
