components/member-profile/member-profile.module.scss, components/pages/index/home-page.module.scss
Fixes #54  
From what I could understand, I had to specify the dimensions of the image so that space can be allocated in the DOM before it loads and doesn't cause the layout to shift suddenly.
Here is a frame from Lighthouse:
Before: 
After:
Looks good to me, but the CLS score is around 0.249 (was around 0.374 before) which means there is scope for improvement.
Please provide your reviews so I can understand more about fixing CLS and eventually help RDS :)
Thank you!
=> Fixing CLS

helper-functions/getPRs.js
Since the API endpoint for fetching PRs has changed from `pullrequests/:username` to `pullrequests/user/:username`, it had to be reflected on the frontend as well.
=> Changed API endpoint for fetching pull requests

helper-functions/urls.js, pages/[id]/index.js, pages/index.js
Closes: #104 
Use the image name returned in the member's data response to fetch the image.
Earlier the image name was hardcoded to `img.png`, so members had to add an image compulsorily named `img.png`.
Now, they just need to ensure that the image they add is correctly described in the `img` key in the member's `data.json`.
For example:
A new member adds their information in the `website-static` project as follows -- 
```
.
├── members
│   ├── anon
│   │   ├── data.json
│   │   └── profile.jpg
```
Then they would need to add it as following in `data.json` -- 
```
{
"id": "anon"
"img": "./profile.jpg",
}
```
=> Fix harcoded image name

components/member-profile/member-profile.module.scss
Solves bug #130
Adding max-height to avoid stretching of badge icons
=> Ensuring proper maximum height for badge icons

package-lock.json, pages/_document.js
@sumitd94 @ankushdharkar Please review this PR
=> seo meta tags for link preview

src/components/designers/index.js, src/components/designers/mock-data.json, src/components/pages/index.js
This PR Contains changes to show designers on the home page.
This is behind the feature flag, to view the designers pass `dev=true` in the query params.
=> Show designers on home page

src/components/member-profile/index.js
FIxed user profile picture display in the profile page, previously it was not showing up
- Expected
- Actual
=> fix profile picture

src/components/UI/navbar/navbar.module.scss, src/components/member-profile/member-profile.module.scss, src/styles/global-styles.scss
Fix navbar to top when scrolling.
Resolves - #339
=> fix navbar on top

src/components/home/index.js
Removal of RDS logo from Home page to replace with members of the week feature.
No
Yes
Before:
After:
=> Remove RDS logo from Home page

src/components/member-role-update/index.js
* **archiveMember** function was invoked infinitely. I modified the function name to a different one.
* [Ticket Link](https://github.com/Real-Dev-Squad/website-members/issues/337)
* Yes, It's a bug
- Steps to repro -> The member should be archived when clicked on the **Archive Member** button
- Expected ->  The member should  be archived and return a success Message
- Actual -> The spinner is infinitely spinning, because of the bug
**Reasons for not testing** :
* I got CORS error when I tried to invoke the **archiveMember** endpoint
* It is a SuperUser functionality
=> Fixed bug with Archive Member functionality

src/components/not-found-page/index.js, src/constants/error-messages.js, src/pages/[id]/index.js
Issue: https://github.com/Real-Dev-Squad/website-members/issues/367
Yes
- Expected
- Actual
Before Anyone can view non-member profile page
After:
Non super-users cannot access non-member profile
=> add Checks for Super User while viewing Non Members Pages

src/components/home/index.js, src/components/member-card/card.module.scss, src/components/member-card/index.js, src/components/new-members/index.js, src/components/user-profile/index.js
This is a stacked PR & should be merged after PR  https://github.com/Real-Dev-Squad/website-members/pull/410
closes #407
No
- Expected
- Actual
=> Make New Users Profile clickable for SuperUsers

src/components/member-card/index.js
Previously, Math.random() was concatenated with the image URL query, which served no purpose in my opinion. The downside of concatenating Math.random() is that each time we navigate to a different page and return, a new number is generated and concatenated with the image URL. When react detects that an asset has not yet been downloaded, it sends a request for the new assets, resulting in all images being downloaded repeatedly when navigating back and forth.
Closes #423 
- Steps to repro - Visit [https://members.realdevsquad.com/](url), click on any member, and check the network tab.
- Expected - Only the image of clicked member has to be downloaded.
- Actual - All the images are being downloaded irrespective of the clicked member 
**Before Changes - When clicking on a particular member** …
=> fix: removed Math.random() from src of <motion.img/>

src/components/member-card/index.js
On the member's site, the section for new users does not show the profile pictures.
This branch closes #444 
- It caused inconvenience in checking out the users and finding the correct ones in case of the same names.
- it also degraded the user experience by seeing a bunch of dummy avatars.
The problem was found in the `member-card` component where we were checking that if the user is a member then show the profile picture else show the default avatar. 
Removed the ternary operator in the `member-card` component's `motion.img` tag to show profile pic if available or show default avatar.
It can be considered a bug, Earlier we were supposed to show the profile pictures of the members only, but as we grew we now have a necessity to show the profile picture of the users as well.
=> Display new users profile picture

jest.config.js, src/components/member-card/index.js, src/components/member-profile/contribution/index.js, src/test/unit/components/member-card/index.test.js
`dev=true` flag removed from contribution task and member card component. A super user will be able to see the setting option with Alt key press without the dev query. 
closes #449
No
A super user should be able to test it.
=> Removed `dev=true` flag.

src/pages/[id]/index.js, src/store/user/user-context.js
closes #428 
The super user context was getting set after some time when the page loads which is why it was giving a flash of 404 error page, added an `isLoading` context which gets set to true when the `setUserPriviledge` function call is made, and it shows a spinner in the whole page while the API call is getting made.
Yes
=> fixed the 404 page flash issue

src/components/member-card/super-user-options/index.js
Added e.stopPropogaion() in show model.
###Bug
When superuser holds the option key and clicks on the setting option, then the app goes to the user page, instead of opening super user options model
=> Fix error for admin, on opening setting model, it going to users page

src/components/keyboard-handler/index.js
#532 
prevented the default behavior of the alt key
Yes
https://github.com/Real-Dev-Squad/website-members/assets/82165483/ff2b4e5d-366e-4b6a-b85e-076c24e38dcf
=> fixed SuperUser edit mode on members site

src/pages/index.js
Currently, new users are filtered based on the `archivedMember` property, which is not coming from the backend so it is undefined. Removed the `archivedMember` check and updated the condition of the filter based on the`in_discord` property.
This will complete the first task of this issue https://github.com/Real-Dev-Squad/website-members/issues/541
Before:
After:
=> FIX: Address issue with missing 'archivedMember' property

src/components/keyboard-handler/index.js, src/components/member-profile/index.js, src/components/member-profile/member-profile.module.scss, src/components/member-role-update/index.js, src/helper-functions/action-handlers.js, src/helper-functions/urls.js
The superuser should be able to promote/demote a member or archive/unarchive a member when the superuser presses the alt key, the settings button appears when clicking on the settings button super user gets a modal where he can perform above mentioned task and the same modal should work on members page as well.
No
> For visual or interaction changes. Can be a video/screenshot.
https://github.com/Real-Dev-Squad/website-members/assets/82165483/98480e94-f5b1-4302-b0bb-f62097b51fef
API is under development so unarchiving and demoting functionality is not built so in UI it's not working but  after the API is built, have created follow-up issue and will handle that in that issue - 
https://github.com/Real-Dev-Squad/website-api-contracts/tree/main/users#patch-usersidtemporarydata 
#548
=> Provide super user option on member detail page

jest.config.js, src/store/keyboard/context.js, src/test/unit/components/member-profile/index.test.js
this fixed the issue of failing tests for member profile page
- Expected
- Actual
=> fix for failing tests in member profile page

src/components/social-media-icon/index.js
When user updating social URL with complete HTTPS request it's get redirect on wrong page
I have checked if Id contain **HTTP** or **HTTPS** ,will abstract user name 
Yes
[](https://github.com/Real-Dev-Squad/website-members/issues/560)
- Expected
- Actual
Before
> For visual or interaction ch
https://github.com/Real-Dev-Squad/website-members/assets/121338813/3908037f-342a-4fde-ace7-077d3088b980
. Can be video / screenshot.
After changes
https://github.com/Real-Dev-Squad/website-members/assets/121338813/2bde2eab-b76a-4dbe-a20f-05358d9ead63
=> Social url issue fix

src/components/member-profile/active-task/index.js, src/components/member-profile/contribution-type/index.js, src/components/member-profile/contribution/index.js, src/constants/error-messages.js, src/helper-functions/taskProgress.js, src/helper-functions/time-was.js, src/test/unit/components/member-profile/index.test.js
Fixes https://github.com/Real-Dev-Squad/website-members/issues/562 
Design Doc: https://docs.google.com/document/d/1JvBDR9Kfo0pzfl-fM7tLZO7WmmRAWbCVFNDgHqnos1k/edit?usp=sharing
If "startedOn" key is falsy i.e undefined/null/0 then completion date should show as 'N/A', so updated timeWas fn to handle this case.
Yes
Go to https://members.realdevsquad.com/amitprakash any member profile and you will see some contribution/task where completion date is NAN sec or 54 years which is invalid.
- Expected
- Actual
- Before
- After
Test results:
=> fixed completion date error msg for falsy start date

src/constants/AppConstants.js, src/helper-functions/urls.js
Fixes: Real-Dev-Squad/todo-action-items#255 
Updates the API endpoint /users/self to /users?profile=true in url.js in helper-function folder and  AppContants.js in constants folder.
No
- Expected
- Actual
No visual changes just updated the api endpoint which is being used in the frontend code.
=> Updated the API endpoint to /users?profile=true in url.js and AppConstants.js
